var express = require("express");
var router = express.Router();
const accountController = require("../app/controllers/AccountController");
router.get("/", accountController.index);
router.post("/register", accountController.register);
router.get("/logins", accountController.logins);
router.get("/changePasswords", accountController.changePasswords);
router.post("/changePassword", accountController.changePassword);
router.post("/login", accountController.login);
router.get("/userInfo/email=:email", accountController.getUserInfo);
module.exports = router;
